const categories = [
  "Popular Books",
  "LGBTQ+",
  "Arts & Photography",
  "Mystery, Thrillers, & Crime",
  "Biography & Memoir",
  "Nonfiction",
  "Business & Investing",
  "Poetry",
  "Children's Books",
  "Romance",
  "Comics & Graphic Novels",
  "Science Fiction",
  "Cooking & Wine",
  "Science & Technology",
  "Fantasy",
  "Self Development & Hobbies",
  "History",
  "Spanish Language",
  "Horror",
  "Spirituality & Religion",
  "Humor & Games",
  "Teen & Young Adult",
  "Literature & Fiction",
  "Travel",
  "Margins Bookstore Month",
];

export default categories;
